import type { OverlayState } from '../../shared/types';
export declare class CyberEngine {
    private canvas;
    private ctx;
    private W;
    private H;
    private glitches;
    private trail;
    private lastGlitch;
    private lastFrameTime;
    private state;
    private audioCapture;
    private audioActive;
    private presenceAlpha;
    private edgeFlash;
    private flashedIds;
    private radarSeenIds;
    private completedSeenIds;
    private donePulses;
    private radarPings;
    private signalEvents;
    private wasActive;
    private awayStart;
    private recapUntil;
    private focusX;
    private focusY;
    private focusInit;
    private focusStrength;
    constructor(canvas: HTMLCanvasElement, state: OverlayState);
    updateState(state: OverlayState): void;
    private syncAudio;
    onMouseInput(x: number, y: number, vx: number, vy: number): void;
    onKeyInput(): void;
    onClickInput(x: number, y: number): void;
    private emitGlitches;
    private systemLoad;
    private presenceTarget;
    private flashEdgeFor;
    private static prune;
    private logSignal;
    private trackPresenceRecap;
    private processAttentionEvents;
    private updateFocus;
    isActive(): boolean;
    render(time: number): void;
}
